source 'https://github.com/CocoaPods/Specs.git' #官方仓库地址
source 'http://10.255.35.174/iov-ios/IFSpecs.git'
use_frameworks!

platform :ios, '10.0'

target 'IFWebSocketKit_Example' do
  pod 'Toast', '~> 4.0.0'
  pod 'Masonry'
  pod 'IFWebSocketKit'
#  pod 'IFWebSocketKit', :path => '../'

  target 'IFWebSocketKit_Tests' do
    inherit! :search_paths

    
  end
end
